POST http://localhost:8082/api/v1/auth
Content-Type: application/x-www-form-urlencoded

username=root&password=root

### Send request with dynamic variables in request's body
POST http://localhost:8082/market-auth/api/v1/auth
Content-Type: application/json

{
  "username": "root",
  "password": "root"
}


### products test
GET http://127.0.0.1:8084/market-app/api/v1/products

### get product byID
GET http://127.0.0.1:8084/market-app/api/v1/products/3


### create product
POST http://127.0.0.1:8084/market-app/api/v1/products
Content-Type: application/json

{
  "title":"Test3",
  "price": "8000",
  "description": "test product"
}


### update product
PUT http://127.0.0.1:8084/market-app/api/v1/products
Content-Type: application/json

{
  "id": "3",
  "title":"Test3",
  "price": "100000",
  "description": "test product updated"
}



### CART SERVICE TEST
GET http://127.0.0.1:8085/market-carts/api/v1/carts/generate_uuid

### add product to cart
GET http://127.0.0.1:8085/market-carts/api/v1/carts/1bc910d7-aed6-4ae8-b05e-3222a489154d/add/3


### add product to cart
GET http://127.0.0.1:8085/market-carts/api/v1/carts/1bc910d7-aed6-4ae8-b05e-3222a489154d


### gateway tests
#### cart
GET http://127.0.0.1:8080/carts/api/v1/carts/generate_uuid

#### auth
POST http://localhost:8080/auth/api/v1/auth
Content-Type: application/json

{
  "username": "root",
  "password": "root"
}


### Spring2 HomeWork12
# поднял keycloak в docker командой:
# docker run -d --name keycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:20.0.3 start-dev
# создал user и client по уроку
# запросил информацию с keycloak командой:
# curl http://localhost:8080/realms/master/.well-known/openid-configuration | jq
# выполнил запрос нижу
# postman не захотел работать
# файл ответа : 2023-02-20T162336.200.json
POST http://localhost:8080/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=test_request&grant_type=password&username=test&password=test
