server:
  port: 8080
jwt:
  secret:
    AuFiEsUwvlnGqQA7u2DtUhaXDAQpaMpt56bi0M88Bmd9d1SmElDK1TtXcbJEC9KPPCKa5J
spring:
  security:
    csrf:
      disabled: true
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods: '*'
            allowed-headers: '*'
#            allow-credentials: true
      routes:
        - id: app-service
          uri: http://localhost:8084
          predicates:
            - Path=/app/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-app
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8085
          predicates:
            - Path=/carts/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-carts
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter
logging:
  level:
    reactor:
      netty: TRACE
    org:
      springframework:
        cloud:
          gateway: TRACE
