server:
  port: 8082
  servlet:
    context-path: /market-auth
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springone
    driver-class-name: org.postgresql.Driver
    username: springone
    password: springone
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
  security:
    csrf:
      disabled: true
jwt:
  secret: AuFiEsUwvlnGqQA7u2DtUhaXDAQpaMpt56bi0M88Bmd9d1SmElDK1TtXcbJEC9KPPCKa5J
  expireTime: 3600000
#logging:
#  level:
#    root: debug
