server:
  port: 8085
  servlet:
    context-path: /carts
integrations:
  product-service:
    url: http://localhost:8189/app/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
