server:
  port: 8085
  servlet:
    context-path: /market-carts
integrations:
  product-service:
    url: http://localhost:8084/market-app/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
